/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutfitIdRouteImport } from './routes/outfit.$id'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitIdRoute = OutfitIdRouteImport.update({
  id: '/outfit/$id',
  path: '/outfit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/inspirations': typeof InspirationsRoute
  '/profile': typeof ProfileRoute
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/inspirations': typeof InspirationsRoute
  '/profile': typeof ProfileRoute
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/inspirations': typeof InspirationsRoute
  '/profile': typeof ProfileRoute
  '/wardrobe': typeof WardrobeRoute
  '/outfit/$id': typeof OutfitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/generate'
    | '/inspirations'
    | '/profile'
    | '/wardrobe'
    | '/outfit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/auth'
    | '/generate'
    | '/inspirations'
    | '/profile'
    | '/wardrobe'
    | '/outfit/$id'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/generate'
    | '/inspirations'
    | '/profile'
    | '/wardrobe'
    | '/outfit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  GenerateRoute: typeof GenerateRoute
  InspirationsRoute: typeof InspirationsRoute
  ProfileRoute: typeof ProfileRoute
  WardrobeRoute: typeof WardrobeRoute
  OutfitIdRoute: typeof OutfitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfit/$id': {
      id: '/outfit/$id'
      path: '/outfit/$id'
      fullPath: '/outfit/$id'
      preLoaderRoute: typeof OutfitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  GenerateRoute: GenerateRoute,
  InspirationsRoute: InspirationsRoute,
  ProfileRoute: ProfileRoute,
  WardrobeRoute: WardrobeRoute,
  OutfitIdRoute: OutfitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
